package escheduler.view.composites;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;

public class EventComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalSplitPanel splitPanel;
	private EventListComposite eventList;
	private EventDetailComposite eventDetail;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EventComposite() {
		buildLayout();
		setCompositionRoot(splitPanel);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalSplitPanel buildLayout() {		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// splitPanel
		splitPanel = new HorizontalSplitPanel();
		splitPanel.setImmediate(false);
		splitPanel.setWidth("100%");
		splitPanel.setHeight("100%");
		
		eventList = new EventListComposite();
		eventDetail = new EventDetailComposite();
		
		splitPanel.addComponent(eventList);
		splitPanel.addComponent(eventDetail);
		
		return splitPanel;
	}

}
