package escheduler.view.composites;

import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;

import escheduler.view.MainView;

/**
 * Custom Vaadin Component that makes use of EventListComposite and EventDetailComposite
 * to display a list of all events a user participates in and the details of a selectable
 * event
 * 
 * @author Freudensprung Fabian
 * @version Jun 1, 2014
 *
 */
public class EventComposite extends CustomComponent {

	private HorizontalSplitPanel splitPanel;
	private EventListComposite eventList;
	private EventDetailComposite eventDetail;
	private MainView mv;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EventComposite(MainView mv) {
		this.mv = mv;
		buildLayout();
		setCompositionRoot(splitPanel);

		// TODO add user code here
	}

	
	private HorizontalSplitPanel buildLayout() {		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// splitPanel
		splitPanel = new HorizontalSplitPanel();
		splitPanel.setImmediate(false);
		splitPanel.setWidth("100%");
		splitPanel.setHeight("100%");
		
		eventList = new EventListComposite(mv);
		eventDetail = new EventDetailComposite();
		
		splitPanel.addComponent(eventList);
		splitPanel.addComponent(eventDetail);
		
		return splitPanel;
	}


	public EventListComposite getEventList() {
		return eventList;
	}


	public void setEventList(EventListComposite eventList) {
		this.eventList = eventList;
	}


	public EventDetailComposite getEventDetail() {
		return eventDetail;
	}


	public void setEventDetail(EventDetailComposite eventDetail) {
		this.eventDetail = eventDetail;
	}

}
