package escheduler.view.composites;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;

import escheduler.controller.EventsController;
import escheduler.view.MainView;
import escheduler.model.Event;

/**
 * Custom Vaadin Component that displays a list of all events a user is either organising
 * or participating in
 *
 * @author Freudensprung Fabian
 * @version Jun 1, 2014
 */
public class EventListComposite extends CustomComponent {
	
	private AbsoluteLayout mainLayout;
	private TabSheet eventTabSheet;
	private Table paEvents;
	private Table myEvents;
	private Panel myPanel;
	private Panel paPanel;
	private MainView mv;
	private EventsController ec;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EventListComposite(MainView mv) {
		this.mv = mv;
		ec = new EventsController();
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// eventTabSheet
		eventTabSheet = buildeventTabSheet();
		List<escheduler.model.Event> list = ec.getEventsForUser(mv.getUser());
		//Adds the Events to the List
		for(int i=0; i<list.size(); i++){
			escheduler.model.Event e = list.get(i);
			String dateText;
			//Checks if the Date has bin set yet
			if(e.getEventdates().size()==1) {
				dateText = ((Date) e.getEventdates().toArray()[0]).toString();
			}
			else {
				dateText = "Date not yet set";
			}
			//Checks if the user is the Organiser
			if(e.getOrganisator().getUsername().equals(mv.getUser().getUsername())) {
				this.addMyEvent(e.getName(), dateText, e.getParticipants().size(), e.getComments().size(), e.getID());
			}
			else {
				this.addParticipatingEvent(e.getName(), e.getOrganisator().getUsername(), dateText, e.getParticipants().size(), e.getComments().size(), e.getID());
			}	
		}
		mainLayout.addComponent(eventTabSheet, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	
	private TabSheet buildeventTabSheet() {
		// common part: create layout
		eventTabSheet = new TabSheet();
		eventTabSheet.setImmediate(true);
		eventTabSheet.setWidth("100%");
		
		// myEvents
		myEvents = new Table();
		myEvents.setImmediate(false);
		myEvents.setSizeFull();
		myEvents.addContainerProperty("Name", String.class, null);
		myEvents.addContainerProperty("Date", String.class, null);
		myEvents.addContainerProperty("Participating", Integer.class, null);
		myEvents.addContainerProperty("Comments", Integer.class, null);
		myPanel = new Panel();
		myPanel.setSizeFull();
		myPanel.setContent(myEvents);
		eventTabSheet.addTab(myPanel, "My Events", null);
		
		
		// paEvents
		paEvents = new Table();
		paEvents.setImmediate(false);
		paEvents.setSizeFull();
		paEvents.addContainerProperty("Name", String.class, null);
		paEvents.addContainerProperty("Organiser", String.class, null);
		paEvents.addContainerProperty("Date", String.class, null);
		paEvents.addContainerProperty("Participating", Integer.class, null);
		paEvents.addContainerProperty("Comments", Integer.class, null);
		paPanel = new Panel();
		paPanel.setSizeFull();
		paPanel.setContent(paEvents);
		eventTabSheet.addTab(paPanel, "Participating", null);
		
		return eventTabSheet;
	}
	
	public Table getPaEvents() {
		return paEvents;
	}


	public void setPaEvents(Table paEvents) {
		this.paEvents = paEvents;
	}

	public Table getMyEvents() {
		return myEvents;
	}


	public void setMyEvents(Table myEvents) {
		this.myEvents = myEvents;
	}


	/**
	 * Adds an Event, that the User created to the table
	 * 
	 * @param name
	 * @param date
	 * @param participating
	 * @param comments
	 */
	public void addMyEvent(String name, String date, Integer participating, Integer comments, Long id) {
		myEvents.addItem(new Object[] {name, date, participating, comments}, id);
	}
	
	/**
	 * Adds an event that the user is participating in to the table
	 * 
	 * @param name
	 * @param organiser
	 * @param date
	 * @param participating
	 * @param comments
	 */
	public void addParticipatingEvent(String name, String organiser, String date, Integer participating, Integer comments, Long id) {
		paEvents.addItem(new Object[] {name, organiser, date, participating, comments}, id);
	}

}
