package escheduler.view.composites;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;

import escheduler.view.MainView;

public class LoggedInComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private TabSheet mainLayout;
	public EventComposite getEvents() {
		return events;
	}

	public void setEvents(EventComposite events) {
		this.events = events;
	}

	public NotificationComposite getNotifications() {
		return notifications;
	}

	public void setNotifications(NotificationComposite notifications) {
		this.notifications = notifications;
	}

	public InvitationComposite getInvitations() {
		return invitations;
	}

	public void setInvitations(InvitationComposite invitations) {
		this.invitations = invitations;
	}

	private EventComposite events;
	private NotificationComposite notifications;
	private InvitationComposite invitations;
	private MainView mv;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param mv 
	 */
	public LoggedInComposite(MainView mv) {
		this.mv=mv;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private TabSheet buildMainLayout() {
		// common part: create layout
		mainLayout = new TabSheet();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		events = new EventComposite();
		mainLayout.addTab(events, "Events", null);
		
		notifications = new NotificationComposite(mv);
		mainLayout.addTab(notifications, "Notifications", null);
		
		invitations = new InvitationComposite(mv);
		mainLayout.addTab(invitations, "Invitations", null);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		return mainLayout;
	}

}
