package escheduler.view.composites;

import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

import escheduler.controller.listener.LoginListener;
import escheduler.view.MainView;


/**
 * Custom Vaadin Component that shows a simple login form
 *
 * @author Freudensprung Fabian
 * @version Jun 1, 2014
 */
public class LoginComposite extends CustomComponent {

	private AbsoluteLayout mainLayout;
	private Button submit;
	private PasswordField password;
	private TextField user;
	private Label heading;
	private Label error;
	private MainView mv;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginComposite(MainView mv) {
		this.mv=mv;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	 
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// heading
		heading = new Label();
		heading.setStyleName("v-label-h1");
		heading.setImmediate(false);
		heading.setWidth("-1px");
		heading.setHeight("-1px");
		heading.setValue("Login");
		mainLayout.addComponent(heading, "top:0.0px;left:0.0px;");
		
		// user
		user = new TextField();
		user.setCaption("Username");
		user.setImmediate(false);
		user.setWidth("-1px");
		user.setHeight("-1px");
		mainLayout.addComponent(user, "top:46.0px;left:0.0px;");
		
		// password
		password = new PasswordField();
		password.setCaption("Password");
		password.setImmediate(false);
		password.setWidth("-1px");
		password.setHeight("-1px");
		mainLayout.addComponent(password, "top:89.0px;left:0.0px;");
		
		// submit
		submit = new Button();
		submit.setCaption("Submit Login");
		submit.setImmediate(false);
		submit.setWidth("-1px");
		submit.setHeight("-1px");
		submit.addClickListener(new LoginListener(mv));
		mainLayout.addComponent(submit, "top:120.0px;left:40.0px;");
		
		return mainLayout;
	}

	public Button getSubmit() {
		return submit;
	}


	public void setSubmit(Button submit) {
		this.submit = submit;
	}


	public PasswordField getPassword() {
		return password;
	}


	public void setPassword(PasswordField password) {
		this.password = password;
	}


	public TextField getUser() {
		return user;
	}


	public void setUser(TextField user) {
		this.user = user;
	}


	public Label getHeading() {
		return heading;
	}


	public void setHeading(Label heading) {
		this.heading = heading;
	}


	public Label getError() {
		return error;
	}


	public void setError(String error) {
		this.error.setValue(error);
	}


	public MainView getMv() {
		return mv;
	}


	public void setMv(MainView mv) {
		this.mv = mv;
	}

}
