package escheduler.view.composites;

import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

/**
 * Custom Vaadin Component that displays a form that is used to create a new events
 *
 * @author Freudensprung Fabian
 * @version Jun 1, 2014
 */
public class NewEventComposite extends CustomComponent {

	private AbsoluteLayout mainLayout;
	
	private Button create;
	
	private ListSelect listSelect_1;
	
	private ComboBox userPicker;
	
	private OptionGroup type;
	
	private PopupDateField datePicker;
	
	private ComboBox dateList;
	
	private TextArea description;
	
	private TextField eventName;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public NewEventComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// eventName
		eventName = new TextField();
		eventName.setCaption("Eventname:");
		eventName.setImmediate(false);
		eventName.setWidth("300px");
		eventName.setHeight("-1px");
		mainLayout.addComponent(eventName, "top:20.0px;left:0.0px;");
		
		// description
		description = new TextArea();
		description.setCaption("Description(Optional):");
		description.setImmediate(false);
		description.setWidth("301px");
		description.setHeight("-1px");
		mainLayout.addComponent(description, "top:68.0px;left:0.0px;");
		
		// dateList
		dateList = new ComboBox();
		dateList.setCaption("Dates:");
		dateList.setImmediate(false);
		dateList.setWidth("140px");
		dateList.setHeight("-1px");
		mainLayout.addComponent(dateList, "top:172.0px;left:0.0px;");
		
		// datePicker
		datePicker = new PopupDateField();
		datePicker.setImmediate(false);
		datePicker.setWidth("-1px");
		datePicker.setHeight("-1px");
		mainLayout.addComponent(datePicker, "top:172.0px;left:160.0px;");
		
		// type
		type = new OptionGroup();
		type.setCaption("Type:");
		type.setImmediate(false);
		type.setWidth("300px");
		type.setHeight("40px");
		type.addItem("One date for all users");
		type.addItem("One date per user");
		mainLayout.addComponent(type, "top:224.0px;left:0.0px;");
		
		// userPicker
		userPicker = new ComboBox();
		userPicker.setCaption("Users:");
		userPicker.setImmediate(false);
		userPicker.setWidth("300px");
		userPicker.setHeight("-1px");
		mainLayout.addComponent(userPicker, "top:287.0px;left:0.0px;");
		
		// listSelect_1
		listSelect_1 = new ListSelect();
		listSelect_1.setImmediate(false);
		listSelect_1.setWidth("301px");
		listSelect_1.setHeight("-1px");
		mainLayout.addComponent(listSelect_1, "top:320.0px;left:0.0px;");
		
		// create
		create = new Button();
		create.setCaption("Create");
		create.setImmediate(false);
		create.setWidth("-1px");
		create.setHeight("-1px");
		mainLayout.addComponent(create, "top:480.0px;left:237.0px;");
		
		return mainLayout;
	}


	public Button getCreate() {
		return create;
	}


	public void setCreate(Button create) {
		this.create = create;
	}


	public ComboBox getUserPicker() {
		return userPicker;
	}


	public void setUserPicker(ComboBox userPicker) {
		this.userPicker = userPicker;
	}


	public OptionGroup getType() {
		return type;
	}


	public void setType(OptionGroup type) {
		this.type = type;
	}


	public PopupDateField getDatePicker() {
		return datePicker;
	}


	public void setDatePicker(PopupDateField datePicker) {
		this.datePicker = datePicker;
	}


	public ComboBox getDateList() {
		return dateList;
	}


	public void setDateList(ComboBox dateList) {
		this.dateList = dateList;
	}


	public String getDescription() {
		return description.getValue();
	}


	public void setDescription(String description) {
		this.description.setValue(description);
	}


	public TextField getEventName() {
		return eventName;
	}


	public void setEventName(TextField eventName) {
		this.eventName = eventName;
	}

}
