package escheduler.Test.Controller;

import escheduler.controller.LoginController;
import junit.framework.TestCase;

/**
 * The class <code>TestLoginController</code> contains tests for the class
 * {@link <code>LoginController</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 30.05.14 12:07
 *
 * @author Ari
 *
 * @version $Revision$
 */
public class TestLoginController extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public TestLoginController(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		// Add additional set up code here
	}

	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
		// Add additional tear down code here
	}

	/**
	 * Run the boolean login(String, String) method test
	 */
	public void testLogin() {
		fail("Newly generated method - fix or disable");
		// add test code here
		LoginController fixture = new LoginController();
		String username = null;
		String password = null;
		boolean result = fixture.login(username, password);
		assertTrue(false);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = true
 * methods = login(QString;!QString;)
 * package = escheduler.Test.Controller
 * package.sourceFolder = eScheduler/src
 * superclassType = junit.framework.TestCase
 * testCase = TestLoginController
 * testClassType = escheduler.controller.LoginController
 */