package escheduler.Test.controller;

import escheduler.controller.LoginController;
import escheduler.controller.RegisterController;
import junit.framework.TestCase;

/**
 * The class <code>TestLoginController</code> contains tests for the class
 * {@link <code>LoginController</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 30.05.14 12:07
 *
 * @author Ari
 *
 * @version $Revision$
 */
public class TestLoginController extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public TestLoginController(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
	}

	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
	}

	/**
	 * Run the boolean login(String, String) method test
	 */
	public void testLogin() {
		RegisterController r1=new RegisterController();
		assertTrue(r1.register("user", "pass"));
		
		LoginController fixture = new LoginController();
		String username = "user";
		String password = "pass";
		boolean result = fixture.login(username, password);
		assertTrue(result);
	}
	
	/**
	 * Run the boolean login(String, String) method test
	 */
	public void testLoginFailure()
	{
		LoginController fixture = new LoginController();
		assertFalse(fixture.login("not", "valid"));
		
		assertFalse(fixture.login(null, "valid"));
		assertFalse(fixture.login(null, null));
		assertFalse(fixture.login("valid", null));
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = true
 * methods = login(QString;!QString;)
 * package = escheduler.Test.controller
 * package.sourceFolder = eScheduler/src
 * superclassType = junit.framework.TestCase
 * testCase = TestLoginController
 * testClassType = escheduler.controller.LoginController
 */