package escheduler.view.composits;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.LoginForm;

public class LoginComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label errorText;
	@AutoGenerated
	private LoginForm loginForm;
	@AutoGenerated
	private Label heading;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// heading
		heading = new Label();
		heading.setStyleName("v-label-h1");
		heading.setImmediate(false);
		heading.setWidth("-1px");
		heading.setHeight("-1px");
		heading.setValue("Login");
		mainLayout.addComponent(heading, "top:0.0px;left:0.0px;");
		
		// loginForm
		loginForm = new LoginForm();
		loginForm.setStyleName("v-loginform");
		loginForm.setImmediate(false);
		loginForm.setWidth("-1px");
		loginForm.setHeight("-1px");
		mainLayout.addComponent(loginForm, "top:30.0px;left:0.0px;");
		
		// errorText
		errorText = new Label();
		errorText.setImmediate(false);
		errorText.setWidth("-1px");
		errorText.setHeight("-1px");
		mainLayout.addComponent(errorText, "top:140.0px;left:0.0px;");
		
		return mainLayout;
	}

}
