package escheduler.view.composits;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

public class NewEventComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button create;
	@AutoGenerated
	private ListSelect listSelect_1;
	@AutoGenerated
	private ComboBox userPicker;
	@AutoGenerated
	private OptionGroup type;
	@AutoGenerated
	private PopupDateField datePicker;
	@AutoGenerated
	private ComboBox dateList;
	@AutoGenerated
	private TextArea description;
	@AutoGenerated
	private TextField eventName;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public NewEventComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// eventName
		eventName = new TextField();
		eventName.setCaption("Eventname:");
		eventName.setImmediate(false);
		eventName.setWidth("300px");
		eventName.setHeight("-1px");
		mainLayout.addComponent(eventName, "top:20.0px;left:0.0px;");
		
		// description
		description = new TextArea();
		description.setCaption("Description(Optional):");
		description.setImmediate(false);
		description.setWidth("301px");
		description.setHeight("-1px");
		mainLayout.addComponent(description, "top:68.0px;left:0.0px;");
		
		// dateList
		dateList = new ComboBox();
		dateList.setCaption("Dates:");
		dateList.setImmediate(false);
		dateList.setWidth("140px");
		dateList.setHeight("-1px");
		mainLayout.addComponent(dateList, "top:172.0px;left:0.0px;");
		
		// datePicker
		datePicker = new PopupDateField();
		datePicker.setImmediate(false);
		datePicker.setWidth("-1px");
		datePicker.setHeight("-1px");
		mainLayout.addComponent(datePicker, "top:172.0px;left:160.0px;");
		
		// type
		type = new OptionGroup();
		type.setCaption("Type:");
		type.setImmediate(false);
		type.setWidth("300px");
		type.setHeight("40px");
		type.addItem("One date for all users");
		type.addItem("One date per user");
		mainLayout.addComponent(type, "top:224.0px;left:0.0px;");
		
		// userPicker
		userPicker = new ComboBox();
		userPicker.setCaption("Users:");
		userPicker.setImmediate(false);
		userPicker.setWidth("300px");
		userPicker.setHeight("-1px");
		mainLayout.addComponent(userPicker, "top:287.0px;left:0.0px;");
		
		// listSelect_1
		listSelect_1 = new ListSelect();
		listSelect_1.setImmediate(false);
		listSelect_1.setWidth("301px");
		listSelect_1.setHeight("-1px");
		mainLayout.addComponent(listSelect_1, "top:320.0px;left:0.0px;");
		
		// create
		create = new Button();
		create.setCaption("Create");
		create.setImmediate(false);
		create.setWidth("-1px");
		create.setHeight("-1px");
		mainLayout.addComponent(create, "top:480.0px;left:237.0px;");
		
		return mainLayout;
	}

}
